/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.Gerenciamento;
import Model.Alugueis;
import Model.Cliente;
import Model.Equipamentos;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author enzov
 */
public class AluguelFrame extends javax.swing.JFrame {

    /**
     * Creates new form AluguelFrame
     */
    public AluguelFrame() {
        initComponents();
        Gerenciamento imprimirClientesComBox = new Gerenciamento();
        for (Cliente cliente : imprimirClientesComBox.listaCLientesComboBox()) {
            comboBoxClientes.addItem("Nome: " + cliente.getNome() + " / ID: " + cliente.getId());
        }
        Gerenciamento imprimirEquipamentosComBox = new Gerenciamento();
        for (Equipamentos equipamento : imprimirEquipamentosComBox.listaEquipamentosComboBox()) {
            if (equipamento.isStatus() == true) {
                comboBoxEquipamentos.addItem("Nome: " + equipamento.getNome() + " / ID: " + equipamento.getId() + " / Valor da Diaria: " + equipamento.getVlLoc());
            }
        }

    }

    private int obterIdClienteSelecionado() {
        String selecionado = (String) comboBoxClientes.getSelectedItem();
        int idCliente = Integer.parseInt(selecionado.split("/ ID: ")[1].trim());
        return idCliente;
    }

    private int obterIdEquipamentoSelecionado() {
        String selecionado = (String) comboBoxEquipamentos.getSelectedItem();
        int idEquipamento = Integer.parseInt(selecionado.split("/ ID: ")[1].split(" / Valor da Diaria: ")[0].trim());
        return idEquipamento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarAluguel = new javax.swing.JButton();
        comboBoxClientes = new javax.swing.JComboBox<>();
        comboBoxEquipamentos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bntRegistarLocacao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textDiasDeAluguel = new javax.swing.JTextField();
        textDataInicioLocacao = new javax.swing.JFormattedTextField();
        labelClienteNomeId = new javax.swing.JLabel();
        labelProdutoNomeId = new javax.swing.JLabel();
        labelDataLocacao = new javax.swing.JLabel();
        labelDataDevolucao = new javax.swing.JLabel();
        labelValorTotalLocacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntVoltarAluguel.setText("VOLTAR");
        bntVoltarAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarAluguelActionPerformed(evt);
            }
        });

        comboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClientesActionPerformed(evt);
            }
        });

        comboBoxEquipamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquipamentosActionPerformed(evt);
            }
        });

        jLabel1.setText("Clientes");

        jLabel2.setText("Equipamentos");

        bntRegistarLocacao.setText("REGISTRAR LOCAÇÃO");
        bntRegistarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistarLocacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Inicio da Locação ");

        jLabel4.setText("Dias de Aluguel");

        textDiasDeAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiasDeAluguelActionPerformed(evt);
            }
        });

        try {
            textDataInicioLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(bntVoltarAluguel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelClienteNomeId)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(textDiasDeAluguel))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textDataInicioLocacao))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(23, 23, 23)
                                    .addComponent(comboBoxEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelProdutoNomeId)
                            .addComponent(labelDataLocacao)
                            .addComponent(labelDataDevolucao)
                            .addComponent(labelValorTotalLocacao))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntRegistarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bntVoltarAluguel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textDiasDeAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textDataInicioLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntRegistarLocacao)
                .addGap(18, 18, 18)
                .addComponent(labelClienteNomeId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProdutoNomeId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataDevolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelValorTotalLocacao)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarAluguelActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntVoltarAluguelActionPerformed

    private void comboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClientesActionPerformed

    }//GEN-LAST:event_comboBoxClientesActionPerformed

    private void comboBoxEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquipamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxEquipamentosActionPerformed

    private void bntRegistarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistarLocacaoActionPerformed

        int diasDeAluguel = Integer.parseInt(textDiasDeAluguel.getText());
        LocalDate dataLocacao = LocalDate.parse(textDataInicioLocacao.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        int idCliente = obterIdClienteSelecionado();
        int idEquipamento = obterIdEquipamentoSelecionado();

        Gerenciamento gerenciarNovoAluguel = new Gerenciamento();
        Alugueis novoAluguel = gerenciarNovoAluguel.cadastrarNovoAluguel(idCliente, idEquipamento, diasDeAluguel, dataLocacao);

        labelClienteNomeId.setText("NOME: " + novoAluguel.getCliente().getNome() + " / ID: " + novoAluguel.getCliente().getId());
        labelProdutoNomeId.setText("EQUIPAMENTO: " + novoAluguel.getProduto().getNome() + " / ID: " + novoAluguel.getProduto().getId());
        labelDataLocacao.setText("DATA DE LOCAÇÃO: " + novoAluguel.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        labelDataDevolucao.setText("DATA DE DEVOLUÇÃO: " + novoAluguel.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        labelValorTotalLocacao.setText("VALOR TOTAL DA LOCAÇÃO: R$ " + novoAluguel.getVlTotalLocacao());

        JOptionPane.showMessageDialog(null, "ALUGUEL CADASTRADO COM SUCESSO");
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntRegistarLocacaoActionPerformed

    private void textDiasDeAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiasDeAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiasDeAluguelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AluguelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AluguelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AluguelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AluguelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AluguelFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegistarLocacao;
    private javax.swing.JButton bntVoltarAluguel;
    private javax.swing.JComboBox<String> comboBoxClientes;
    private javax.swing.JComboBox<String> comboBoxEquipamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelClienteNomeId;
    private javax.swing.JLabel labelDataDevolucao;
    private javax.swing.JLabel labelDataLocacao;
    private javax.swing.JLabel labelProdutoNomeId;
    private javax.swing.JLabel labelValorTotalLocacao;
    private javax.swing.JFormattedTextField textDataInicioLocacao;
    private javax.swing.JTextField textDiasDeAluguel;
    // End of variables declaration//GEN-END:variables
}
