/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.Gerenciamento;
import Model.Cliente;
import Model.Equipamentos;
import Model.Alugueis;
import Model.Administrador;
import Model.Pessoa;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author enzov
 */
public class CadProdutosFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadProdutosFrame
     */
    public CadProdutosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntVoltarCadProdutos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textNomeProduto = new javax.swing.JTextField();
        bntCadProdutos = new javax.swing.JButton();
        LabelProdutoCadastrado = new javax.swing.JLabel();
        LabelProdutoNome = new javax.swing.JLabel();
        LabelProdutoId = new javax.swing.JLabel();
        textValorDaLocacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LabelValorDaDiaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE  PRODUTOS");

        bntVoltarCadProdutos.setText("VOLTAR");
        bntVoltarCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarCadProdutosActionPerformed(evt);
            }
        });

        jLabel2.setText("NOME");

        bntCadProdutos.setText("CADASTRAR");
        bntCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadProdutosActionPerformed(evt);
            }
        });

        jLabel3.setText("VALOR DA DIARIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(bntCadProdutos))
                                .addComponent(textValorDaLocacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                .addComponent(textNomeProduto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelProdutoNome)
                                    .addComponent(LabelValorDaDiaria)
                                    .addComponent(LabelProdutoId)
                                    .addComponent(LabelProdutoCadastrado)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntVoltarCadProdutos)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bntVoltarCadProdutos)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textValorDaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(bntCadProdutos)
                .addGap(2, 2, 2)
                .addComponent(LabelProdutoCadastrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelProdutoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelProdutoId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelValorDaDiaria)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarCadProdutosActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova

        LabelProdutoCadastrado.setText("");
        LabelProdutoNome.setText("");
        LabelProdutoId.setText("");
    }//GEN-LAST:event_bntVoltarCadProdutosActionPerformed

    private void bntCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadProdutosActionPerformed

        // Verifica se o valor digitado é um número real
        String text = textValorDaLocacao.getText();
        double valorLocacao = 0;
        boolean testVlLocacao = false;

        try {
            valorLocacao = Double.parseDouble(text);
            testVlLocacao = true;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "ERRO: DIGITE UM NÚMERO REAL");
            return; // Sai do método se o valor não for válido
        }

        // Verifica se o valor da locação é válido (opcional)
        if (valorLocacao <= 0) {
            JOptionPane.showMessageDialog(null, "ERRO: O VALOR DA LOCAÇÃO DEVE SER MAIOR QUE ZERO");
            return; // Sai do método se o valor não for válido
        }

        // Cria o novo produto e atualiza os rótulos
        Gerenciamento criarProduto = new Gerenciamento();
        Equipamentos novoProduto = criarProduto.cadastrarProduto(textNomeProduto.getText(), 0, valorLocacao, true);

        LabelProdutoCadastrado.setText("Produto cadastrado com sucesso!");
        LabelProdutoNome.setText("NOME: " + novoProduto.getNome());
        LabelProdutoId.setText("ID: " + novoProduto.getId());
        LabelValorDaDiaria.setText("VALOR DA DIARIA: R$" + novoProduto.getVlLoc());

        textNomeProduto.setText("");
        textValorDaLocacao.setText("");
    }//GEN-LAST:event_bntCadProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdutosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProdutosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelProdutoCadastrado;
    private javax.swing.JLabel LabelProdutoId;
    private javax.swing.JLabel LabelProdutoNome;
    private javax.swing.JLabel LabelValorDaDiaria;
    private javax.swing.JButton bntCadProdutos;
    private javax.swing.JButton bntVoltarCadProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textValorDaLocacao;
    // End of variables declaration//GEN-END:variables
}
