/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.Gerenciamento;

/**
 *
 * @author enzov
 */
public class CentralRelatoriosFrame extends javax.swing.JFrame {

    /**
     * Creates new form CentralRelatoriosFrame
     */
    public CentralRelatoriosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarCentralRelatorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bntTodosAlugueis = new javax.swing.JButton();
        bntAluguelAtivo = new javax.swing.JButton();
        bntALuguelInativo = new javax.swing.JButton();
        bntClientesCadastrados = new javax.swing.JButton();
        bntEquipamentosCadastrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntVoltarCentralRelatorios.setText("VOLTAR");
        bntVoltarCentralRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarCentralRelatoriosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("CENTRAL DE RELATÓRIOS");

        bntTodosAlugueis.setText("TODOS ALUGUEIS + FATURAMENTO TOTAL");
        bntTodosAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTodosAlugueisActionPerformed(evt);
            }
        });

        bntAluguelAtivo.setText("ALUGUEIS ATIVOS ");
        bntAluguelAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAluguelAtivoActionPerformed(evt);
            }
        });

        bntALuguelInativo.setText("ALUGUEIS INATIVOS");
        bntALuguelInativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntALuguelInativoActionPerformed(evt);
            }
        });

        bntClientesCadastrados.setText("CLIENTES CADASTRADOS ");
        bntClientesCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClientesCadastradosActionPerformed(evt);
            }
        });

        bntEquipamentosCadastrados.setText("EQUIPAMENTOS CADASTRADOS ");
        bntEquipamentosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEquipamentosCadastradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntVoltarCentralRelatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntTodosAlugueis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntAluguelAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntALuguelInativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntClientesCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntEquipamentosCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bntVoltarCentralRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bntTodosAlugueis)
                .addGap(18, 18, 18)
                .addComponent(bntAluguelAtivo)
                .addGap(18, 18, 18)
                .addComponent(bntALuguelInativo)
                .addGap(18, 18, 18)
                .addComponent(bntClientesCadastrados)
                .addGap(18, 18, 18)
                .addComponent(bntEquipamentosCadastrados)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarCentralRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarCentralRelatoriosActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntVoltarCentralRelatoriosActionPerformed

    private void bntTodosAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTodosAlugueisActionPerformed
        Gerenciamento relatorioAlugueis = new Gerenciamento();
        relatorioAlugueis.relatorioTodosAlugueis();
    }//GEN-LAST:event_bntTodosAlugueisActionPerformed

    private void bntAluguelAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAluguelAtivoActionPerformed
        Gerenciamento relatorioAlugueis = new Gerenciamento();
        relatorioAlugueis.relatorioAluguelAtivo();
    }//GEN-LAST:event_bntAluguelAtivoActionPerformed

    private void bntALuguelInativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntALuguelInativoActionPerformed
        Gerenciamento relatorioAlugueis = new Gerenciamento();
        relatorioAlugueis.relatorioAluguelInativo();
    }//GEN-LAST:event_bntALuguelInativoActionPerformed

    private void bntClientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClientesCadastradosActionPerformed
        Gerenciamento relatorioAlugueis = new Gerenciamento();
        relatorioAlugueis.relatorioClientesCadastrados();
    }//GEN-LAST:event_bntClientesCadastradosActionPerformed

    private void bntEquipamentosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEquipamentosCadastradosActionPerformed
      Gerenciamento relatorioAlugueis = new Gerenciamento();
      relatorioAlugueis.relatorioEquipamentosCadastrados();
    }//GEN-LAST:event_bntEquipamentosCadastradosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CentralRelatoriosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CentralRelatoriosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CentralRelatoriosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CentralRelatoriosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CentralRelatoriosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntALuguelInativo;
    private javax.swing.JButton bntAluguelAtivo;
    private javax.swing.JButton bntClientesCadastrados;
    private javax.swing.JButton bntEquipamentosCadastrados;
    private javax.swing.JButton bntTodosAlugueis;
    private javax.swing.JButton bntVoltarCentralRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
