/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.Gerenciamento;
import Model.Alugueis;
import Model.Cliente;
import Model.Equipamentos;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author enzov
 */
public class ConsultaLocacoesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaLocacoes
     */
    public ConsultaLocacoesFrame() {
        initComponents();
        Gerenciamento imprimirClientesComBox = new Gerenciamento();
        for (Cliente cliente : imprimirClientesComBox.listaCLientesComboBox()) {
            comboBoxNomeConsulta.addItem("Nome: " + cliente.getNome() + " / ID: " + cliente.getId());
        }
        Gerenciamento imprimirEquipamentosComBox = new Gerenciamento();
        for (Equipamentos equipamento : imprimirEquipamentosComBox.listaEquipamentosComboBox()) {

            comboBoxEquipamentoConsulta.addItem("Nome: " + equipamento.getNome() + " / ID " + equipamento.getId());
        }
    }

    private int obterIdClienteSelecionado() {
        String selecionado = (String) comboBoxNomeConsulta.getSelectedItem();
        int idCliente = Integer.parseInt(selecionado.split("/ ID: ")[1].trim());
        return idCliente;
    }

    private int obterIdEquipamentoSelecionado() {
        String selecionado = (String) comboBoxEquipamentoConsulta.getSelectedItem();
        int idEquipamento = Integer.parseInt(selecionado.split("/ ID ")[1].trim());
        return idEquipamento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        consultaPorNome = new javax.swing.JPanel();
        comboBoxNomeConsulta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaConsultaNome = new javax.swing.JTextArea();
        bntConsultaNome = new javax.swing.JButton();
        voltarLocacoesCliente = new javax.swing.JButton();
        consultaPorEquipamento = new javax.swing.JPanel();
        bntVoltarLocacoesEquip = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxEquipamentoConsulta = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaConsultaEquipamento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboBoxNomeConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxNomeConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNomeConsultaActionPerformed(evt);
            }
        });

        jLabel1.setText("CLIENTE");

        textAreaConsultaNome.setColumns(20);
        textAreaConsultaNome.setRows(5);
        jScrollPane1.setViewportView(textAreaConsultaNome);

        bntConsultaNome.setText("CONSULTA");
        bntConsultaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultaNomeActionPerformed(evt);
            }
        });

        voltarLocacoesCliente.setText("VOLTAR");
        voltarLocacoesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarLocacoesClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaPorNomeLayout = new javax.swing.GroupLayout(consultaPorNome);
        consultaPorNome.setLayout(consultaPorNomeLayout);
        consultaPorNomeLayout.setHorizontalGroup(
            consultaPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPorNomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consultaPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntConsultaNome)
                    .addGroup(consultaPorNomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(consultaPorNomeLayout.createSequentialGroup()
                .addGroup(consultaPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPorNomeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(consultaPorNomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarLocacoesCliente)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        consultaPorNomeLayout.setVerticalGroup(
            consultaPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPorNomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltarLocacoesCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultaPorNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNomeConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntConsultaNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("NOME", consultaPorNome);

        bntVoltarLocacoesEquip.setText("VOLTAR");
        bntVoltarLocacoesEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarLocacoesEquipActionPerformed(evt);
            }
        });

        jLabel2.setText("EQUIPAMENTO");

        comboBoxEquipamentoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxEquipamentoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxEquipamentoConsultaActionPerformed(evt);
            }
        });

        jButton1.setText("CONSULTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textAreaConsultaEquipamento.setColumns(20);
        textAreaConsultaEquipamento.setRows(5);
        jScrollPane2.setViewportView(textAreaConsultaEquipamento);

        javax.swing.GroupLayout consultaPorEquipamentoLayout = new javax.swing.GroupLayout(consultaPorEquipamento);
        consultaPorEquipamento.setLayout(consultaPorEquipamentoLayout);
        consultaPorEquipamentoLayout.setHorizontalGroup(
            consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                .addGroup(consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxEquipamentoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bntVoltarLocacoesEquip))))
                    .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        consultaPorEquipamentoLayout.setVerticalGroup(
            consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                .addGroup(consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntVoltarLocacoesEquip))
                    .addGroup(consultaPorEquipamentoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(consultaPorEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxEquipamentoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("EQUIPAMENTO", consultaPorEquipamento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarLocacoesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarLocacoesClienteActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_voltarLocacoesClienteActionPerformed

    private void bntConsultaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultaNomeActionPerformed

        int idCliente = obterIdClienteSelecionado();
        Gerenciamento gerenciarConsultaAluguel = new Gerenciamento();
        ArrayList<Alugueis> aluguelsConsulta = gerenciarConsultaAluguel.consultaAluguelNome(idCliente);

        if (aluguelsConsulta.isEmpty()) {
            textAreaConsultaNome.append("Nenhum aluguel encontrado para este cliente.\n");
        } else {
            for (Alugueis aluguelConsulta : aluguelsConsulta) {
                textAreaConsultaNome.append("Cliente: " + aluguelConsulta.getCliente().getNome() + " / ID: " + aluguelConsulta.getCliente().getId());
                textAreaConsultaNome.append("\nEquipamento: " + aluguelConsulta.getProduto().getNome() + " / ID: " + aluguelConsulta.getProduto().getId());
                textAreaConsultaNome.append("\nValor total da locação: R$" + aluguelConsulta.getVlTotalLocacao());
                textAreaConsultaNome.append("\nData de locação: " + aluguelConsulta.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                textAreaConsultaNome.append("\nData de devolução: " + aluguelConsulta.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                if (aluguelConsulta.isStatus()) {
                    textAreaConsultaNome.append("\nStatus: ATIVO");
                } else {
                    textAreaConsultaNome.append("\nStatus: INATIVO");
                }
                textAreaConsultaNome.append("\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n");
            }
        }
    }//GEN-LAST:event_bntConsultaNomeActionPerformed

    private void comboBoxNomeConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNomeConsultaActionPerformed
        textAreaConsultaNome.setText("");
    }//GEN-LAST:event_comboBoxNomeConsultaActionPerformed

    private void bntVoltarLocacoesEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarLocacoesEquipActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntVoltarLocacoesEquipActionPerformed

    private void comboBoxEquipamentoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxEquipamentoConsultaActionPerformed
        textAreaConsultaEquipamento.setText("");
    }//GEN-LAST:event_comboBoxEquipamentoConsultaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idEquipamento = obterIdEquipamentoSelecionado();
        Gerenciamento gerenciarConsultaAluguel = new Gerenciamento();
        ArrayList<Alugueis> aluguelsConsultaEquipamentos = gerenciarConsultaAluguel.consultaAluguelEquipamento(idEquipamento);

        if (aluguelsConsultaEquipamentos.isEmpty()) {
            textAreaConsultaEquipamento.append("Nenhum aluguel encontrado para este equipamento.\n");
        } else {
            for (Alugueis aluguelConsulta : aluguelsConsultaEquipamentos) {
                textAreaConsultaEquipamento.append("Cliente: " + aluguelConsulta.getCliente().getNome() + " / ID: " + aluguelConsulta.getCliente().getId());
                textAreaConsultaEquipamento.append("\nEquipamento: " + aluguelConsulta.getProduto().getNome() + " / ID: " + aluguelConsulta.getProduto().getId());
                textAreaConsultaEquipamento.append("\nValor total da locação: R$" + aluguelConsulta.getVlTotalLocacao());
                textAreaConsultaEquipamento.append("\nData de locação: " + aluguelConsulta.getDataLocacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                textAreaConsultaEquipamento.append("\nData de devolução: " + aluguelConsulta.getDataDevolucao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
                if (aluguelConsulta.isStatus()) {
                    textAreaConsultaEquipamento.append("\nStatus: ATIVO");
                } else {
                    textAreaConsultaEquipamento.append("\nStatus: INATIVO");
                }
                textAreaConsultaEquipamento.append("\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaLocacoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaLocacoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaLocacoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaLocacoesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaLocacoesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConsultaNome;
    private javax.swing.JButton bntVoltarLocacoesEquip;
    private javax.swing.JComboBox<String> comboBoxEquipamentoConsulta;
    private javax.swing.JComboBox<String> comboBoxNomeConsulta;
    private javax.swing.JPanel consultaPorEquipamento;
    private javax.swing.JPanel consultaPorNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea textAreaConsultaEquipamento;
    private javax.swing.JTextArea textAreaConsultaNome;
    private javax.swing.JButton voltarLocacoesCliente;
    // End of variables declaration//GEN-END:variables
}
