/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controler.Gerenciamento;
import Model.Alugueis;
import Model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author enzov
 */
public class DevolucaoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DevolucaoFrame
     */
    public DevolucaoFrame() {
        initComponents();
        Gerenciamento imprimirClientesComBoxDevolucao = new Gerenciamento();
        for (Cliente cliente : imprimirClientesComBoxDevolucao.listaCLientesComboBox()) {
            comboBoxClienteDevolucao.addItem("Nome: " + cliente.getNome() + " / ID: " + cliente.getId());
        }
    }

    private int obterIdClienteSelecionado() {
        String selecionado = (String) comboBoxClienteDevolucao.getSelectedItem();
        int idCliente = Integer.parseInt(selecionado.split("/ ID: ")[1].trim());
        return idCliente;
    }

    private int obterIdEquipamentoSelecionado() {
        String selecionado = (String) comboBoxProdutoDevolucao.getSelectedItem();
        int idEquipamento = Integer.parseInt(selecionado.split("/ ID ")[1].trim());
        return idEquipamento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bntVoltarDevolucao = new javax.swing.JButton();
        comboBoxClienteDevolucao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxProdutoDevolucao = new javax.swing.JComboBox<>();
        bntCadDevolucao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntVoltarDevolucao.setText("VOLTAR");
        bntVoltarDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarDevolucaoActionPerformed(evt);
            }
        });

        comboBoxClienteDevolucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxClienteDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClienteDevolucaoActionPerformed(evt);
            }
        });

        jLabel2.setText("CLIENTE");

        jLabel1.setText("PRODUTOS LOCADOS");

        comboBoxProdutoDevolucao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "." }));
        comboBoxProdutoDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProdutoDevolucaoActionPerformed(evt);
            }
        });

        bntCadDevolucao.setText("CADASTRAR DEVOLUÇÃO");
        bntCadDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadDevolucaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntCadDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntVoltarDevolucao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxProdutoDevolucao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxClienteDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bntVoltarDevolucao)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxClienteDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxProdutoDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntCadDevolucao)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarDevolucaoActionPerformed
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntVoltarDevolucaoActionPerformed

    private void bntCadDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadDevolucaoActionPerformed

        int idClienteDevolucao = obterIdClienteSelecionado();
        int idProdutoDevolucao = obterIdEquipamentoSelecionado();

        Gerenciamento gerenciarDevolucao = new Gerenciamento();
        gerenciarDevolucao.devolucaoProdutos(idClienteDevolucao, idProdutoDevolucao);

        JOptionPane.showMessageDialog(null, "DEVOLUÇÃO CADASTRADA COM SUCESSO");
        MainFrame n = new MainFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova
    }//GEN-LAST:event_bntCadDevolucaoActionPerformed

    private void comboBoxClienteDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteDevolucaoActionPerformed

        comboBoxProdutoDevolucao.removeAllItems();

        Gerenciamento imprimirEquipamentosComBoxDevolucao = new Gerenciamento();

        int idCliente = obterIdClienteSelecionado();

        for (Alugueis aluguel : imprimirEquipamentosComBoxDevolucao.listaAluguelComboBox()) {
            if (aluguel.getCliente().getId() == idCliente && aluguel.getProduto().isStatus() == false) {
                comboBoxProdutoDevolucao.addItem("Nome: " + aluguel.getProduto().getNome() + " / ID " + aluguel.getProduto().getId());
            }

        }
    }//GEN-LAST:event_comboBoxClienteDevolucaoActionPerformed

    private void comboBoxProdutoDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProdutoDevolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxProdutoDevolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevolucaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevolucaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevolucaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevolucaoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevolucaoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadDevolucao;
    private javax.swing.JButton bntVoltarDevolucao;
    private javax.swing.JComboBox<String> comboBoxClienteDevolucao;
    private javax.swing.JComboBox<String> comboBoxProdutoDevolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
