/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Cliente;
import Model.Equipamentos;
import Model.Alugueis;
import Model.Administrador;
import Model.Pessoa;
import java.util.ArrayList;

/**
 *
 * @author enzov
 */
public class MainFrame extends javax.swing.JFrame {

    private ArrayList<Cliente> listaClientes;
    private static ArrayList<Equipamentos> listaEquipamentos = new ArrayList<>(); // Vetor Cadastro de Equipamentos
    private static ArrayList<Alugueis> listaAluguel = new ArrayList<>();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        listaClientes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bntCadClientes = new javax.swing.JButton();
        bntVoltar = new javax.swing.JButton();
        bntCadProdutos = new javax.swing.JButton();
        bntAluguelEquipamentos = new javax.swing.JButton();
        bntDevolucaoEquipamentos = new javax.swing.JButton();
        bntRelatorios = new javax.swing.JButton();
        bntConsultaLocacoes = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bntCadClientes.setText("CADASTRO DE CLIENTES");
        bntCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadClientesActionPerformed(evt);
            }
        });

        bntVoltar.setText("VOLTAR");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        bntCadProdutos.setText("CADASTRO DE PRODUTOS");
        bntCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadProdutosActionPerformed(evt);
            }
        });

        bntAluguelEquipamentos.setText("ALUGUEL DE EQUIPAMENTOS");
        bntAluguelEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAluguelEquipamentosActionPerformed(evt);
            }
        });

        bntDevolucaoEquipamentos.setText("DEVOLUÇÃO DE EQUIPAMENTOS");
        bntDevolucaoEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDevolucaoEquipamentosActionPerformed(evt);
            }
        });

        bntRelatorios.setText("CENTRAL DE RELATÓRIOS");
        bntRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatoriosActionPerformed(evt);
            }
        });

        bntConsultaLocacoes.setText("CONSULTA DE LOCAÇÕES");
        bntConsultaLocacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConsultaLocacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntVoltar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bntCadClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntCadProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntAluguelEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntDevolucaoEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntConsultaLocacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntVoltar)
                .addGap(8, 8, 8)
                .addComponent(bntCadClientes)
                .addGap(18, 18, 18)
                .addComponent(bntCadProdutos)
                .addGap(18, 18, 18)
                .addComponent(bntAluguelEquipamentos)
                .addGap(18, 18, 18)
                .addComponent(bntDevolucaoEquipamentos)
                .addGap(18, 18, 18)
                .addComponent(bntConsultaLocacoes)
                .addGap(18, 18, 18)
                .addComponent(bntRelatorios)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
        LoginFrame n = new LoginFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova   
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void bntCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadClientesActionPerformed
        CadClientesFrame n = new CadClientesFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova 
    }//GEN-LAST:event_bntCadClientesActionPerformed

    private void bntCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadProdutosActionPerformed
        CadProdutosFrame n = new CadProdutosFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova         // TODO add your handling code here:
    }//GEN-LAST:event_bntCadProdutosActionPerformed

    private void bntAluguelEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAluguelEquipamentosActionPerformed

        AluguelFrame n = new AluguelFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova   
    }//GEN-LAST:event_bntAluguelEquipamentosActionPerformed

    private void bntDevolucaoEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDevolucaoEquipamentosActionPerformed
        DevolucaoFrame n = new DevolucaoFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova  
    }//GEN-LAST:event_bntDevolucaoEquipamentosActionPerformed

    private void bntRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatoriosActionPerformed
        CentralRelatoriosFrame n = new CentralRelatoriosFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova  
    }//GEN-LAST:event_bntRelatoriosActionPerformed

    private void bntConsultaLocacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConsultaLocacoesActionPerformed
        ConsultaLocacoesFrame n = new ConsultaLocacoesFrame(); //Inicializa a tela nova
        this.dispose(); //fecha tela que estavamos
        n.setVisible(true); // Mostra  a tela nova 
    }//GEN-LAST:event_bntConsultaLocacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAluguelEquipamentos;
    private javax.swing.JButton bntCadClientes;
    private javax.swing.JButton bntCadProdutos;
    private javax.swing.JButton bntConsultaLocacoes;
    private javax.swing.JButton bntDevolucaoEquipamentos;
    private javax.swing.JButton bntRelatorios;
    private javax.swing.JButton bntVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
